feat: add args core schema
linterhub/schema pull request #144
Opened 2018-07-10 22:13 UTC by svoboda-rabstvo

added `args.json` core schema

Closes #107

2018-07-11 19:17 UTC, xferra commented on src/schema/args.json
> +                "hideName": {
`named` seems to be a better wording, what do u think?

2018-07-11 20:18 UTC, xferra submitted a review, later dismissed
What is the reason to repeat official schema definitions there?

2018-07-11 20:20 UTC, xferra requested changes
What is the reason to repeat official schema definitions there?

2018-07-12 09:48 UTC, svoboda-rabstvo commented
If I remove it, we can't to validate arguments later

2018-07-12 09:55 UTC, svoboda-rabstvo commented on src/schema/args.json
> +                "hideName": {
I rename it, thx

2018-07-12 10:14 UTC, xferra commented
Well, then why they were not listed in the previous version? (in rm repo)

2018-07-12 10:22 UTC, svoboda-rabstvo commented
It's [here](https://github.com/repometric/linterhub/blob/master/schema/args.json#L25)

2018-07-12 10:24 UTC, xferra commented
I mean why do we need to repeat [types, enum definitions, etc.](https://github.com/linterhub/schema/pull/144/files#diff-bd55d66a1d79b8cc07468c0f7f485f89R61) that are already specified in JSON Schema?

2018-07-12 10:30 UTC, svoboda-rabstvo commented
I can remove it

2018-07-12 15:26 UTC, xferra commented on src/schema/args.json
> +                "Named": {
Uppercase?

2018-07-12 15:27 UTC, xferra commented on src/schema/args.json
> +                    "description": "Hide orignal name. Used when package have multiple arguments without prefix.",
Please be careful, we never use dot at the end

2018-07-12 15:28 UTC, xferra commented on src/schema/args.json
> +        "argument": {
Then argument it's just a property as defined in json schema, isn't it?

2018-07-12 18:28 UTC, romanrostislavovich commented on src/schema/args.json
> +        "argument": {
Yes

2018-07-12 18:29 UTC, svoboda-rabstvo commented on src/schema/args.json
> +                    "description": "Hide orignal name. Used when package have multiple arguments without prefix.",
I will fix it

2018-07-12 18:29 UTC, svoboda-rabstvo commented on src/schema/args.json
> +                "Named": {
I will fix it

2018-07-27 14:34 UTC, xferra commented on src/schema/args.json
> +        "argument": {
Still, why do we need to duplicate it's definition if we can reuse it from JSON Schema?

2018-07-27 14:35 UTC, xferra commented on src/schema/args.json
> +        "argument": {
Ah, we have custom definition for`id` and extra properties.

2018-07-27 16:23 UTC, svoboda-rabstvo commented on src/schema/args.json
> +        "argument": {
I'm not sure, but we don't have duplicate it. Maybe you mean a create separate JSON Schema for it?

2018-07-27 22:46 UTC, xferra commented on src/schema/args.json
> +        "argument": {
I mean that this is a schema that defines a new args schema. Could you please test whether it's actually is able to validate args json? If it's still is not clear - ping me directly.

2018-07-28 14:04 UTC, xferra commented
@svoboda-rabstvo Please check my variant #165

2018-07-30 08:50 UTC, svoboda-rabstvo commented
I will close it. Finished in #165

2018-07-30 08:50 UTC, closed without merging