ci: add semantic release for master
linterhub/schema pull request #35
Opened 2018-06-15 14:25 UTC by svoboda-rabstvo

added semantic release to a project, include:
- changelog
- release to GitHub
- automatic update version in core schemas
- automatic update version in package.json

Closes #30

2018-06-15 17:05 UTC, xferra commented on .travis.yml
> +  - npm install travis-deploy-once
I think they're also dev deps for the whole project, right?

2018-06-15 17:05 UTC, xferra commented on package.json
> +    "update": "git fetch && git rebase && git submodule update --remote --merge",
As we agreed, let's use 1 way of interacting with git, please rewrite it.

2018-06-15 17:06 UTC, xferra requested changes
FYI

2018-06-17 14:05 UTC, svoboda-rabstvo commented on .travis.yml
> +  - npm install travis-deploy-once
done

2018-06-17 14:05 UTC, svoboda-rabstvo commented on package.json
> +    "update": "git fetch && git rebase && git submodule update --remote --merge",
done

2018-06-17 20:32 UTC, xferra commented
Reimplemented in #39

2018-06-17 20:32 UTC, closed without merging