docs: add doc describing collection schema
linterhub/schema pull request #75
Opened 2018-06-22 19:42 UTC by svoboda-rabstvo

added doc describing collection schema

Part of #70

2018-06-22 21:37 UTC, xferra commented on docs/schema/collection.md
> +    "definitions":{
This is not an example, but just a part of the schema.

2018-06-22 21:38 UTC, xferra commented on docs/schema/collection.md
> +| enum | string[] | + | An Array names of language |
Is language array names + array of extensions?

2018-06-22 21:41 UTC, xferra requested changes
I actually do not sure WHY this PR was created, coz there is no direct use of those objects and example do not demonstrate the structure or possible values. Let's keep it open while all other schemas will be finished. I recommend to document only core schemas and start with `package`.

2018-07-05 10:29 UTC, xferra commented
@svoboda-rabstvo How do you think, do we still need this kind of doc?

2018-07-05 12:22 UTC, svoboda-rabstvo commented
I think, no

2018-07-05 13:46 UTC, xferra commented
Then please close PR with some descriptive comment 👍

2018-07-19 22:32 UTC, xferra commented
Closing this as far as docs for core schemas will provided in scope of another PR next week.

2018-07-19 22:32 UTC, closed without merging