docs: contributing file fill
linterhub/schema pull request #79
Opened 2018-06-27 11:06 UTC by svoboda-rabstvo

following blocks in `CONTRIBUTING.md` file are fill out:
- `contributing`
- `issue`
- `pull request`

Part of #17

2018-06-29 15:31 UTC, xferra commented
@svoboda-rabstvo Please close this one or update as soon as #102 was merged.

2018-07-05 10:15 UTC, xferra commented on .github/CONTRIBUTING.md
> +# Contributing to @linterhub/schema
Generic header imho was better: fewer words to change from repo to repo.

2018-07-05 10:16 UTC, xferra commented on .github/CONTRIBUTING.md
> +
I'd like to see some `welcome` phrases here if u don't mind.

2018-07-05 10:16 UTC, xferra commented on .github/CONTRIBUTING.md
> +Please take into account some restrictions:
Restrictions, do they?

2018-07-05 10:17 UTC, xferra commented on .github/CONTRIBUTING.md
> +If you want to suggest a Major Feature, please first submit an issue and describe
Unclear what is major feature, let's simplify the doc, so potential contributors will not be force to read a lot of rules.

2018-07-05 10:18 UTC, xferra commented on .github/CONTRIBUTING.md
> +Good pull requests - patches, improvements, new features - are a great help.
Agai, keep it as small and descriptive as possible, the rest - into PR template.

2018-07-05 10:19 UTC, xferra commented on .github/CONTRIBUTING.md
> +git submodule update --init
Why submodule step was skipped?

2018-07-05 10:19 UTC, xferra commented on .github/CONTRIBUTING.md
> +git checkout develop
Checkout should be before `npm install`.

2018-07-05 10:20 UTC, xferra commented on .github/CONTRIBUTING.md
> +> Note: More information about creating a fork and cloning your fork to local folder read in [`git help`][github-help-fork]
How to setup reference to `upstream`? May be some guide?

2018-07-05 10:20 UTC, xferra commented on .github/CONTRIBUTING.md
> +gulp build-test
Incorrect cmd.

2018-07-05 10:21 UTC, xferra commented on .github/CONTRIBUTING.md
> +- The change causes no functional regression. Be sure to run a test to verify your changes before submitting a pull request.
Is the checklist a part of the PR template?

2018-07-05 10:21 UTC, xferra commented on .github/CONTRIBUTING.md
>  ### Commit message
You can split this doc if it becomes more than 1 page. Just keep it simple.

2018-07-05 10:22 UTC, xferra commented on .github/CONTRIBUTING.md
>  ### Commit message
and instead of explaining widely used format we can just reference a guide, what do u think?

2018-07-05 10:22 UTC, xferra commented on .github/CONTRIBUTING.md
> +[github-url-issue-bug-reporter]: ../../issues/new?template=Bug_report.md
Relative links will not work there, unfortunately.

2018-07-05 10:23 UTC, xferra commented on .github/CONTRIBUTING.md
> +[github-url-issue-custom]: ../../issues/new?template=Custom.md
A link to template wizard will be better

2018-07-05 10:23 UTC, xferra commented on script/gulp/task.lint.js
> -const markdownlintConfig = require(`../../${config.src.config.markdownlint}`);
Why this config was removed?

2018-07-05 10:24 UTC, xferra commented on script/gulp/task.lint.js
>  const js = () => gulp
Then do we need this empty (logically) peace of gulp? :)

2018-07-05 12:24 UTC, romanrostislavovich commented on .github/CONTRIBUTING.md
> +- The change causes no functional regression. Be sure to run a test to verify your changes before submitting a pull request.
Yes

2018-07-05 12:25 UTC, romanrostislavovich commented on .github/CONTRIBUTING.md
> +# Contributing to @linterhub/schema
Ok, i fix it

2018-07-05 19:37 UTC, xferra commented on .github/CONTRIBUTING.md
> +- The change causes no functional regression. Be sure to run a test to verify your changes before submitting a pull request.
Then let's remove from this doc?

2018-07-05 19:58 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +- The change causes no functional regression. Be sure to run a test to verify your changes before submitting a pull request.
Ok

2018-07-16 15:52 UTC, xferra commented
@svoboda-rabstvo Do you plan to finish this doc?

2018-07-16 15:57 UTC, svoboda-rabstvo commented
@xferra Yes of course

2018-07-17 13:18 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
>  ### Commit message
Sounds good, but where to put it?

2018-07-17 13:18 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +[github-url-issue-bug-reporter]: ../../issues/new?template=Bug_report.md
I will fix it

2018-07-17 13:18 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +[github-url-issue-custom]: ../../issues/new?template=Custom.md
I will fix it

2018-07-17 13:18 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +gulp build-test
I will fix it

2018-07-17 13:20 UTC, svoboda-rabstvo commented on script/gulp/task.lint.js
>  const js = () => gulp
Yes, for run linting locally

2018-07-17 14:16 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +
Done

2018-07-17 14:16 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +Please take into account some restrictions:
Fix it

2018-07-17 14:17 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +If you want to suggest a Major Feature, please first submit an issue and describe
Done

2018-07-17 14:17 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +Good pull requests - patches, improvements, new features - are a great help.
Done

2018-07-17 14:17 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +git submodule update --init
Done

2018-07-17 14:17 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +git checkout develop
Done

2018-07-17 14:19 UTC, svoboda-rabstvo commented on script/gulp/task.lint.js
> -const markdownlintConfig = require(`../../${config.src.config.markdownlint}`);
I create a separate issue for it

2018-07-19 22:35 UTC, xferra commented on .github/CONTRIBUTING.md
>  ### Commit message
If we have a good, already documented, example - just as a link, otherwise - `template` repo (`./docs/`) is the best place IMHO.

2018-07-19 22:37 UTC, xferra commented on .github/CONTRIBUTING.md
> +You can send you questions in [`@linterhub/maintens`][maintainers] or create
I disabled team discussions (GitHub feature), should I re-enable it?

2018-07-19 22:37 UTC, xferra commented on .github/CONTRIBUTING.md
> +> Note: More information about creating a fork and cloning your fork to local folder read in [`git help`][github-help-fork]
@svoboda-rabstvo Not relevant, ty for updates.

2018-07-19 22:39 UTC, xferra commented on .github/CONTRIBUTING.md
> +#### STEP 5: Create a new branch
If steps are too small, maybe numbered list is better than headers `####`?

2018-07-19 22:43 UTC, xferra commented on .github/CONTRIBUTING.md
>  ### Commit message
As an example: `template\docs\git\commit_message.md` or smth like that for the explanation below. As an alternative a link to an advanced explanation like https://conventionalcommits.org/ (we can also use exactly this style, why not).

2018-07-19 22:44 UTC, xferra requested changes
Please review my suggestions above.

2018-07-20 07:50 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +You can send you questions in [`@linterhub/maintens`][maintainers] or create
Yes, we use that link in another projects

2018-07-27 17:04 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +You can send you questions in [`@linterhub/maintens`][maintainers] or create
I enable discussions

2018-07-27 17:17 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
>  ### Commit message
done

2018-07-27 17:20 UTC, svoboda-rabstvo commented on .github/CONTRIBUTING.md
> +#### STEP 5: Create a new branch
I changed it to `###` and some steps include great description

2018-08-05 09:37 UTC, xferra approved these changes
+1

2018-08-05 09:39 UTC, merged