ci: add install all npm packages after cleanup
linterhub/schema pull request #93
Opened 2018-06-28 13:57 UTC by svoboda-rabstvo

added next gulp commands:
- `install:npm` - installing all npm packages from `package.json`. Use only with another gulp task.

Closes #90

2018-06-28 20:26 UTC, xferra commented on script/gulp/task.test.js
> +        done();
It's unclear why you reverting this change after I've (probably) fixed it a few days ago. This way `done` will be never executed if the test passed, right?

2018-06-28 20:27 UTC, xferra commented on script/gulp/task.install.js
> +        args: ['--save-dev'],
Why save dev?

2018-06-28 20:30 UTC, xferra commented on gulpfile.js
> +gulp.task('clean', gulp.series('clean:all', 'install:npm'));
So, if `clean:build` failed somehow - `install:npm` will not be executed, right? Then it's more logical to (just schematic idea):

```javascript
task('clean', 
parallel
[
series(clean-node, install) <--- reinstall actually,
clean-build
clean-release
etc.
]
```

2018-06-28 20:31 UTC, xferra commented on gulpfile.js
> +gulp.task('clean', gulp.series('clean:all', 'install:npm'));
BTW, as for me`install:npm` sunds like `we gonna install npm itself`, any better name?

2018-06-28 20:32 UTC, xferra requested changes
FYI

2018-06-29 10:07 UTC, svoboda-rabstvo commented on script/gulp/task.install.js
> +        args: ['--save-dev'],
Because, all packages in ours `package.json` install as `dev`

2018-06-29 10:34 UTC, svoboda-rabstvo commented on script/gulp/task.test.js
> +        done();
was fixed

2018-06-29 10:34 UTC, svoboda-rabstvo commented on gulpfile.js
> +gulp.task('clean', gulp.series('clean:all', 'install:npm'));
done

2018-07-05 02:39 UTC, xferra commented on script/gulp/task.install.js
> +        args: ['--save-dev'],
This command expected to install packages listed in `package.json`. It should not install any new packages, so this arg is not needed.

2018-07-05 10:10 UTC, xferra reviewed
+1

2018-07-05 10:12 UTC, xferra commented
@svoboda-rabstvo Please resolve conflicts.

2018-07-05 10:53 UTC, svoboda-rabstvo commented
done

2018-07-05 13:40 UTC, xferra approved these changes
+1

2018-07-05 13:45 UTC, merged